### PR TITLE
Modify relative to absolute indexing for Person list, find and edit

### PR DESCRIPTION
**Pull request by crazoter**
Added Model.refreshFilteredPersonList (See ModelManager.refreshFilteredPersonList) in order to refresh the display after a DeleteCommand

Removed 2 irrelevant tests.

### CODE REVIEW

**Comment by gabrielchao** [comment]
Looks good. However, should `refreshFilteredPersonList()` be part of the `Model` interface? It seems like refreshing should be the internal responsibility of the `ModelManager` implementation whenever a data change is made. Therefore, would an external class ever have to worry about calling this method? If not, maybe the method could be private in `ModelManager`?

**Comment by crazoter** [comment]
Hmm, I believe it is necessary because consider now that one can modify the source list without modifying the filtered list. There is now a necessity to be able to update the filtered list without modifying the predicate in order to reflect the changes. The refreshFilteredPersonList would be unnecessary if one extends updateFilteredPersonList() to take in null values, but I feel this complicates the method and also makes things less clear, hence I decided to add the refreshFilteredPersonList method.

**Comment by cheongsiuhong** [comment]
> Hmm, I believe it is necessary because consider now that one can modify the source list without modifying the filtered list. There is now a necessity to be able to update the filtered list without modifying the predicate in order to reflect the changes. The refreshFilteredPersonList would be unnecessary if one extends updateFilteredPersonList() to take in null values, but I feel this complicates the method and also makes things less clear, hence I decided to add the refreshFilteredPersonList method.

Then wouldn't it be better if all the methods within `ModelManager` that alter the source list refresh the filtered list as well? I believe that commands do not need access to the `refreshFilteredPersonList` command.

**Comment by crazoter** [comment]
Hmm, fair point when you point out that commands don't have need to access it and thus it's a implementation concern than an interface concern. I have made it private. Thanks @gabrielchao & @cheongsiuhong.

**Pull request merged**
